### ISSUE TITLE
[cleanup] Update types in constants for semantic correctness

### ISSUE THREAD

**Issue by jsturdy** [cms-gem-daq-project/ctp7_modules#108]
## Brief summary of issue
Would like to update all the constants to have a type that semantically represents the information they are storing (see [discussion](https://github.com/cms-gem-daq-project/ctp7_modules/pull/107#discussion_r269985743) )

### Types of issue
- [x] Maintenance (request for change which cleans up codebase)

**Comment by lpetre-ulb** [comment]
Moved to the new GitLab repository, [cmsgemos#86](https://gitlab.cern.ch/cmsgemonline/cmsgemos/-/issues/86).
