### ISSUE TITLE
Ambiguous call to sleep (potential bug)

### ISSUE THREAD

**Issue by lmoureaux** [cms-gem-daq-project/ctp7_modules#128]
## Brief summary of issue

One can find the following call to [`sleep(unsigned)`](https://linux.die.net/man/3/sleep) at [`src/optohybrid.cpp:465`](https://github.com/cms-gem-daq-project/ctp7_modules/blob/develop/src/optohybrid.cpp#L465):
```cpp
sleep(0.1);
```
This is compiled as `sleep(0)` and therefore there's no real sleep.

`clang` 6 warns:
```
src/optohybrid.cpp:465:15: warning: implicit conversion from 'double' to 'unsigned int' changes value from 0.1 to 0 [-Wliteral-conversion]
        sleep(0.1);
        ~~~~~ ^~~
1 warning generated.
```

### Types of issue

- [x] Bug report (report an issue with the code)
- [ ] Feature request (request for change which adds functionality)

## Expected Behavior

If a call to `sleep(0)` is intended, use that instead. If a waiting time of 0.1s is intended, use `std::this_thread::sleep_for(std::chrono::milliseconds(100))` (the C++ version is safer because it's not sensitive to signals).

## Current Behavior

Code is unclear.

## Your Environment

* `clang` 6.0.0
* GNU `libc` 2.27

**Comment by lpetre-ulb** [comment]
No longer present in the new repository.
