### ISSUE TITLE
Update system-specific hw constants

### ISSUE THREAD

**Issue by mexanick** [cms-gem-daq-project/ctp7_modules#136]
## Brief summary of issue
Certain refactoring and update is required to address the differences in SCA-related hw constants. The constants types also has to be standardized as well as loop counters data types in few other instances. 

### Types of issue

- [ ] Bug report (report an issue with the code)
- [x] Feature request (request for change which adds functionality)

**Comment by lpetre-ulb** [comment]
Fixed in #132, the GE2/1 compatibility PR.
