### ISSUE TITLE
[Bug Report] undefined namespace used in calibration_routines

### ISSUE THREAD

**Issue by AndrewLevin** [cms-gem-daq-project/ctp7_modules#152]
`develop` branch of ctp7_modules fails to compile due to this line:

https://github.com/cms-gem-daq-project/ctp7_modules/blob/develop/src/calibration_routines.cpp#L712

in which `amc` is not defined.

##  Brief summary of issue

This is hardcoded to 12 in other places e.g.:

https://github.com/cms-gem-daq-project/ctp7_modules/blob/develop/src/calibration_routines.cpp#L720

### Types of issue

- [x] Bug report (report an issue with the code)
- [ ] Feature request (request for change which adds functionality)

### Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Shell used:

**Comment by mexanick** [comment]
you should use branch `release/v1.1.X` instead of `develop`
