### ISSUE TITLE
[feature request] Variable length s-bit rate scan

### ISSUE THREAD

**Issue by jsturdy** [cms-gem-daq-project/ctp7_modules#154]
## Brief summary of issue
In order to better understand the tail of the s-bit rate threshold scan, we will need the ability to set the acquisition time for the `sbitRateScanParallel` function (and associated functions in `vfatqc`, `xhal`, and `cmsgemos`

### Types of issue
- [x] Feature request (request for change which adds functionality)

## Expected Behavior
Ability to take an s-bit rate threshold scan with higher statistics at each point

## Current Behavior
Acquisition is hard coded to 1 second acquisition

## Possible Solution (for bugs)
* one additional parameter to set the acquisition time (in seconds)
* 'rate` stored in the tree (`vfatqc`) as the number of hits divided by this rate

## Context
Should be developed for the current operational SW
* `ctp7_modules` : [`release/v1.1.X`](https://github.com/cms-gem-daq-project/ctp7_modules/tree/release/v1.1.X)
* `vfatqc`: [`rpc-playground`](https://github.com/cms-gem-daq-project/vfatqc-python-scripts/tree/rpc-playground)
* `cmsgemos`: [`generic-amc-RPC-v3-short-term`](https://github.com/cms-gem-daq-project/cmsgemos/tree/generic-amc-RPC-v3-short-term)
* `xhal`: [`legacyPreBoost`](https://github.com/cms-gem-daq-project/xhal/tree/legacyPreBoost)
* `gemplotting`: [`develop`](https://github.com/cms-gem-daq-project/gem-plotting-tools)

**Comment by lpetre-ulb** [comment]
Closed in #155.
