### ISSUE TITLE
Standardization of RPC Modules rsp/res Words

### ISSUE THREAD

**Issue by bdorney** [cms-gem-daq-project/ctp7_modules#6]
## Brief summary of issue

Function arguments inside ctp7 RPC modules are not uniform.  For example we have:

- `oh_number` vs. `ohN`,
- `scanReg` vs `regName` 

While this is not critical it might make for easier long-term maintenance if we developed some standard naming convention and then kept a file with a description, e.g.:

```
Parameter Name    Description
ohN   Optohybrid number
scanReg    Register to be passed to scan applications
...
...
``` 

Or instead of a separate file the above could just be a table in the `README.md` of this repository.

Low priority.

### Types of issue

- [ ] Bug report (report an issue with the code)
- [X] Feature request (request for change which adds functionality)

## Context (for feature requests)

Unifies RPC set/get word commands, etc...

**Comment by mexanick** [comment]
Apart from simple var names it is important to have well-defined names for labels in RPC messages.
