### ISSUE TITLE
Development flow implementation

### ISSUE THREAD

**Issue by mexanick** [cms-gem-daq-project/ctp7_modules#7]
## Brief summary of issue

Please make PRs to the develop branch of the repository. Master branch should remain stable at all times. When a sufficient confidence in the code correctness is received, the develop branch will be merged into master. The only reason to make a direct PRs to the master is hotfixes for bugs.

**Comment by jsturdy** [comment]
```
sudo yum install git-flow
cd <repo>
git flow init
# profit
```

**Comment by bdorney** [comment]
Further reading: https://danielkummer.github.io/git-flow-cheatsheet/

Branching model base: http://nvie.com/posts/a-successful-git-branching-model/
