### ISSUE TITLE
Update RPM spec file

### ISSUE THREAD

**Issue by mexanick** [cms-gem-daq-project/ctp7_modules#78]
## Brief summary of issue

In order to be able to install the package at the CTP7 with `smart` package manager, following modifications are required:
1. Makefile should be altered such that a package-specific `spec` file is used instead of `specTemplate.spec` (or after copying the `specTemplate.spec` extra modifications are made to it... however, this is less favorable approach)
2. New spec file should **not** contain any pre-install or post-install scripts
3. Automated addition of dependencies by `rpm` should be disabled (`AutoReqProv: no`)
4. Install location should be set to `/mnt/persistent/rpcmodules` so the `rpcsvc` will find the new modules
### Types of issue

- [ ] Bug report (report an issue with the code)
- [x] Feature request (request for change which adds functionality)

## Expected Behavior

Resulting `rpm` should be installable by `smart` in its current state/configuration and usable by `rpcsvc`
## Current Behavior

Because of `smart` being unaware of standard packages installed on the card, automatic dependencies cause critical installation error. Secondly, current install path does not meet requirements posed by `rpcsvc`

## Your Environment

* Version used:
CTP7 with `CTP7-GENERIC-20181114T140852-0600-e84f2b0` PetaLinux image
* Shell used:

**Comment by jsturdy** [comment]
1 is taken care of by:

https://github.com/cms-gem-daq-project/gembuild/blob/34a0cff58073ff518f07c4fcebfd63393794dbf3/mfRPMRules.mk#L40-L49
