### ISSUE TITLE
Feature Request: add a broadcastRead(...) method

### ISSUE THREAD

**Issue by bdorney** [cms-gem-daq-project/ctp7_modules#9]
## Brief summary of issue

Would like to have a `broadcastRead(...)` method added to:

- `include/optohybrid.h`
-`src/optohbyrid.cc`

Should work in conjunction with [this](https://github.com/cms-gem-daq-project/xhal/pull/26) xhal PR to work.

### Types of issue

- [ ] Bug report (report an issue with the code)
- [X] Feature request (request for change which adds functionality)

## Expected Behavior

Should have both a non-local and a local version.
Syntax for local version expected:

broadcastReadLocal(lmdb::txn & rtxn, lmdb::dbi & dbi, std::string oh_number, std::string reg_to_read, uint32_t * result, RPCMsg * response, uint32_t mask = 0xFF000000)

The RPC request should  set the following:
- word `oh_number`
- word `mask`
- string `reg_name`

The RPC response should allow to `get_word_array` called `data` which is assumed to be a 1D array of size 24 where the array idx is the VFAT number, e.g. `data[0]` corresponds to `VFAT0`. 

Should read the AMC FW version of the CTP7, then:

- if major FW version <= 2 should perform a broadcast using the OHv2b broadcast FW functionality.  
- if major FW version > 2 should just loop over 24 vfats in order to read the requested `reg_name` and return the value.
 
## Current Behavior

No `broadcastRead(...)` method exists.

## Context (for feature requests)

Will unlock a lot of the current uhal functionality in xhal.

**Comment by mexanick** [comment]
I doubt we need a different implementation for the broadcastRead. The reason is that current v2b FW design requires you to read the broadcast result N times where N is the number of VFATs you've read. 
So at the end instead of doing N reads, you're doing a write (submit broadcast read request) + N reads.
